sudo: required

services:
  - docker

## Make sure all containers build without error.

before_install: 
  - docker build -t nareal/r_docker_tidyverse_spiced_preview .

## Crude test, see if our container stays up after launch
script:
  - docker run -ti nareal/r_docker_tidyverse_spiced_preview R --version
  - docker run -d --name rstudio nareal/r_docker_tidyverse_spiced_preview
  - sleep 5 && docker ps | grep r_docker_tidyverse_spiced_preview
  - docker rm -f $(docker ps -a -q)

 
notifications:
  email:
    recipients:
      - nareal@gmail.com
    on_success: always
    on_failure: always
